events {}

http {
    upstream read_api {
        server read-api-1:8080;
        server read-api-2:8080;
    }

    upstream write_api {
        server write-api:8080;
    }

    server {
        listen 80;

        location = /urls {
            proxy_pass http://write_api;
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://read_api;
            proxy_set_header Host $host;
        }
    }
}
