events {}

http {
    upstream read_api {
        server host.docker.internal:5300;
        server host.docker.internal:5301;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://read_api;
            proxy_set_header Host $host;
        }
    }
}
